# 接口是内部系统接口还是外部，默认外部
rest.external=false
# 若接口是内部的话 只需写@RequestMapping部分即可
rest.app=hdsp-streaming
# 是否走网关 默认走网关进行访问 否则直接用该服务ip:port访问
rest.useGateway=true
# rest.uri=http://172.23.16.65:8080/xstr/v1/0/sql-jobs/test
rest.uri=xstr/v1/0/sql-jobs/test
rest.method=POST
rest.contentType=application/json
rest.body={"jobCode":"testJobCode01","clusterCode":"testClusterCode","sqlUploadPath":"sqlUploadPath","content":"content"}

# 接口授权信息 内部请求暂时只支持grantType=PASSWORD 从配置文件读取
rest.auth=OAUTH2
rest.grantType=PASSWORD
# rest.clientId=client
# rest.clientSecret=secret
# rest.tokenUri=http://172.23.16.65:8080/oauth/oauth/token
# rest.username=admin
# rest.password=GTwNoMxLrfSK1Rfq4JySZn9cPIJfQlQVCCmOfVCI+xpGUwUYgyQ+xgRCJO/vhly1rNs/toCwmezzazfj4uv9bw==

# 主业务逻辑接口启用失败重试，默认关闭
rest.retry.enabled=true
# 默认重试3次
rest.retry.number=3
# 异步回调启用 查询接口执行状态，默认关闭
rest.callback.enabled=true
# rest.callback.uri=http://172.23.16.65:8080/xstr/v1/0/sql-jobs/test/testJobCode01
# 注意这里没有/
rest.callback.uri=xstr/v1/0/sql-jobs/test/testJobCode01
# 是否走网关 默认走网关进行访问 否则直接用该服务ip:port访问
rest.callback.useGateway=true
rest.callback.app=hdsp-streaming
# 单位秒，默认5秒
rest.callback.interval=25
# 最多异步状态接口查询3次，默认3次
rest.callback.number=3
# 状态接口查询3次后，若还是running或failed，则结束任务，默认是success即true
rest.callback.finishSuccess=true
# callback回调返回json解析的key
rest.callback.responseKey=status
# callback回调返回json解析的value
rest.callback.responseValue=FINISHED

type=rest